/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.12.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.2.5")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.github.muffindud.temptake.App"
}

// shadowJar
tasks.shadowJar {
    archiveBaseName.set("temptake")
    archiveClassifier.set("")
    archiveVersion.set("")
    archiveExtension.set("jar")
    mergeServiceFiles()
    manifest {
        attributes(
            "Main-Class" to "com.github.muffindud.temptake.App"
        )
    }
}